apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
  name: {{ include "frontend.fullname" . }}
  namespace: {{ .Release.Namespace }}
data:
  {{- with .Values.config.data }}
  {{- toYaml . | nindent 2 }}
  {{- end }}