{{- if eq .Values.workload.kind "StatefulSet" }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "frontend.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  serviceAccountName: {{ include "frontend.serviceAccountName" . }}
  serviceName: {{ include "frontend.fullname" . }}-headless
  replicas: {{ .Values.workload.replicas }}
  selector:
    matchLabels:
      {{- include "frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "frontend.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.workload.image }}
          ports:
            - name: {{ .Chart.Name }}-port
              containerPort: {{ .Values.workload.containerPort }}
          volumeMounts:
            - name: data
              mountPath: /app/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ {{ .Values.persistence.accessMode }} ]
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
{{- end }}
